name: silcam
channels:
    - anaconda
    - cogsci     # Channel for pygame
dependencies:    # These are the conda packages
    - python=3.5
    - pip=10.0.1
    - conda-forge::libffi=3.2.1
    - numpy=1.15.2
    - scipy=1.0.0
    - pandas=0.20.3
    - openpyxl=2.4.8
    - matplotlib=3.0.0
    - imageio=2.4.1
    - scikit-image=0.14.0
    - pygame=1.9.2
    - tensorflow=1.9.0
    - h5py=2.8.0
    - psutil=5.4.7
    - Sphinx=1.7.9
    - pyserial=3.4
    - seaborn=0.9.0
    - pytables=3.4.4
    - pytest
    - xarray==0.13.0
    - pip: # The following packages are installed with pip
        - xlrd
        - configparser==3.5.0
        - docopt==0.6.2
        - cmocean==1.2
        - tqdm==4.28.1
        - setuptools==40.2.0
        - sphinx_rtd_theme==0.4.2
        - sphinxcontrib-napoleon==0.7
        - tflearn==0.3.2
        - PyQt5==5.10
        - cmocean==1.2
        - pytest-error-for-skips==2.0.2
        - names==0.3.0
