name: silcam
channels:
    - conda-forge
dependencies:    # These are the conda packages
    - python=3.8
    - pip
    - pandas
    - scipy
    - matplotlib
    - h5py=2.10.0
    - pytables=3.6.1
    - scikit-image
    - openpyxl=3.0.5
    - imageio=2.9.0
    - psutil=5.7.2
    - Sphinx=3.2.1
    - pyserial=3.4
    - seaborn=0.11.0
    - pytest=6.1.1
    - PyQt=5.12.3
    - xarray=0.16.2
    - pip: # The following packages are installed with pip
        - tensorflow.cpu==2.10.0
        - pygame==2.0.0.dev22
        - xlrd==1.2.0
        - configparser==5.0.1
        - docopt==0.6.2
        - cmocean==2.0
        - tqdm==4.51.0
        - setuptools==50.3.2
        - sphinx_rtd_theme==0.5.0
        - sphinxcontrib-napoleon==0.7
        - pytest-error-for-skips==2.0.2
        - names==0.3.0
