name: silcam
channels:
    - anaconda
dependencies:    # These are the conda packages
    - python=3.6
    - pip
    - pandas=1.1.3
    - scipy=1.5.2
    - matplotlib=3.3.1
    - tensorflow=1.9.0
    - h5py
    - pytables
    - scikit-image
    - openpyxl
    - imageio
    - psutil
    - Sphinx
    - pyserial
    - seaborn
    - pytest
    - pip: # The following packages are installed with pip
        - pygame
        - xlrd
        - configparser==3.5.0
        - docopt==0.6.2
        - cmocean==1.2
        - tqdm==4.28.1
        - setuptools==40.2.0
        - sphinx_rtd_theme==0.4.2
        - sphinxcontrib-napoleon==0.7
        - PyQt5==5.10
        - cmocean==1.2
        - pytest-error-for-skips==2.0.2
