name: Docker build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build the Docker image
        run: docker build . -f Dockerfile -t my-image-name
    
      - name: Run the tests
        run: docker run pysilcam
