name: Docker build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: whoan/docker-build-with-cache-action@v4
        with:
          #push_image_and_stages: true  # useful when you are setting a workflow to run on PRs
          username: tankefugl
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          #registry: Docker registry (default: Docker Hub's registry).
          image_name: tankefugl/pysilcam #sintef/pysilcam?
          image_tag: github-ci
          context: .
          dockerfile: Dockerfile

      # - name: Build the Docker image
      #   run: docker build . -f Dockerfile -t pysilcam

      - name: Download test data
        shell: bash
        env:
          AZURE_TEST_DATA_ACCESS_TOKEN: ${{ secrets.AZURE_TEST_DATA_ACCESS_TOKEN }}
        run: |
          wget -nv https://pysilcam.blob.core.windows.net/test-data/pysilcam-testdata.zip?$AZURE_TEST_DATA_ACCESS_TOKEN -O temp.zip
          unzip temp.zip

      - name: Inspect testdata
        run: docker run -v $PWD/pysilcam-testdata:/testdata tankefugl/pysilcam:github-ci ls /testdata -al

      - name: Run the tests
        run: docker run -v $PWD/pysilcam-testdata:/testdata tankefugl/pysilcam:github-ci
