name: Docker build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Checkout test data
        uses: actions/checkout@v2
        with:
          repository: SINTEF/pysilcam-testdata
          lfs: true
          path: testdata

      - name: Build the Docker image
        run: docker build . -f Dockerfile -t pysilcam

      - name: Run the tests
        run: docker run -v testdata:/testdata pysilcam

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.4
          architecture: x64

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'lint'   # NOTE: this needs to be the same as the job name


