name: Windows build and test

on: [push, pull_request]

env:
  IMAGE_NAME: sintef/pysilcam
  IMAGE_TAG: github-ci

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 60

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download test data
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "https://pysilcam.blob.core.windows.net/test-data/pysilcam-testdata.zip"
          target: temp.zip

      - name: Unzip test data
        shell: powershell
        run: 7z x temp.zip -otestdata

      - name: Setup test
        shell: cmd /C CALL {0}
        run: >-
          dir &&