name: Windows build and test

on: [push, pull_request]

env:
  IMAGE_NAME: sintef/pysilcam
  IMAGE_TAG: github-ci

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 60

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install silcam environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yml

      - name: Check silcam environment
        shell: cmd /C CALL {0}
        run: >-
          conda info && conda list

      - name: Setup develop
        shell: cmd /C CALL {0}
        run: >-
          activate silcam &&
          python setup.py develop

      - name: Download test data
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "https://pysilcam.blob.core.windows.net/test-data/pysilcam-testdata.zip"
          target: temp.zip

      - name: Unzip test data
        shell: powershell
        run: 7z x temp.zip -o testdata

      - name: Setup test
        shell: cmd /C CALL {0}
        run: >-
          set UNITTEST_DATA_PATH='testdata\pysilcam-testdata\unittest-data' &&
          set SILCAM_MODEL_PATH='testdata\pysilcam-testdata\keras_model.h5 &&
          python setup.py test_noskip