name: Windows build and test

on: [push, pull_request]

env:
  IMAGE_NAME: sintef/pysilcam
  IMAGE_TAG: github-ci

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 60

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install silcam environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yml

      - name: Check silcam environment
        shell: powershell
        run: |
          conda info
          conda list

      - name: Download test data
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "https://pysilcam.blob.core.windows.net/test-data/pysilcam-testdata.zip"
          target: temp.zip

      - name: Unzip test data
        uses: montudor/action-zip@v0.1.1
        with:
          args: unzip -qq temp.zip -d testdata