name: Docker build and test

on: [push, pull_request]

env:
  IMAGE_NAME: sintef/pysilcam
  IMAGE_TAG: github-ci

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 60

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install silcam environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yml
      - run: |
          conda info
          conda list


